# Generated by Django 4.2 on 2024-08-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="view_cnt",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
