# Generated by Django 4.2 on 2024-08-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_view_cnt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="updaetd_at",
            new_name="updated_at",
        ),
    ]
