# Generated by Django 4.2 on 2024-08-22 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                related_name="user_followings", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="followings",
            field=models.ManyToManyField(
                related_name="user_followers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
